
- hosts: all
  user: root
  vars_files:
  - env_variables
  tasks:

  - name: "Install extra packages"
    package: name={{item}} state=present
    with_items:
      - aide
      - apt-transport-https
      - bzip2
      - ca-certificates
      - chrony
      - conntrack
      - conntrackd
      - curl
      - ebtables
      - ethtool
      - gnupg-agent
      - htop
      - iptraf-ng
      - lsof
      - nano
      - net-tools
      - netdata
      - netstat-nat
      - socat
      - software-properties-common
      - sshguard
      - tor
      - ufw
      - unzip
      - util-linux
      - vim
      - zip

  - name: Add group "monero" to remote server
    group:
       name: monero
       gid: 2012
       state: present 
  
  - name: Add user "monero" to remote server
    user:
       name: monero
       uid: 2001
       group: monero
       shell: /bin/bash

  - name: Creating a new directory
    file:
      path: /var/run/monero
      owner: monero
      group: monero
      state: directory
  
  - name: Creating a new directory
    file:
      path: /var/log/monero
      owner: monero
      group: monero
      state: directory
  
  - name: Creating a new directory
    file:
      path: /etc/monero
      owner: monero
      group: monero
      state: directory

  - name: Creating monero config file
    file:
      path: /etc/monero/monerod.conf
      owner: monero
      group: monero
      state: touch

  - name: Copying torrc to remote server
    copy:
      src: artifacts/torrc
      dest: /etc/tor/torrc
      owner: root
      group: root

  - name: Restart tor service
    systemd:
      state: restarted
      enabled: yes
      daemon_reload: yes
      name: tor

  - name: Get Tor hostname from /var/lib/tor/monero/hostname
    shell: cat /var/lib/tor/monero/hostname
    register: tor_monero_hostname

  - debug:
      msg: "Your current onion hostname is {{ tor_monero_hostname.stdout }}:18089"

  - debug:
      msg: "Remove /var/lib/tor/monero directory if you need a new onion hostname"

  - name: Copy monero node configuration file from template
    template:
      src: monerod.conf.j2
      dest: /etc/monero/monerod.conf

  - name: Creating monero service config file
    file:
      path: /etc/systemd/system/monerod.service
      owner: monero
      group: monero
      state: touch
  
  - name: Copy monero service configuration file from template
    template:
      src: monerod.service.j2
      dest: /etc/systemd/system/monerod.service

  - name: Download latest 64-bit binaries
    get_url: url=https://downloads.getmonero.org/cli/linux64 dest=/tmp/monero-linux-x64.tar.bz2

  - name: Unarchive
    unarchive:
      remote_src: yes
      src: /tmp/monero-linux-x64.tar.bz2
      dest: /usr/local/bin/
      owner: monero
  
  - name: Copying monerod
    copy:
      remote_src: yes
      src: /usr/local/bin/monero-x86_64-linux-gnu-{{ monerod_version }}/monerod
      dest: /usr/local/bin/
      owner: monero
      group: monero
      mode: 0777

  - name: Copying monero banned ip list to remote server
    copy:
      src: artifacts/monero-ban-list.txt
      dest: /etc/monero/monero-ban-list.txt
      owner: monero
      group: monero

  - name: Load the new systemd script for monerod and start the monerod service
    systemd:
      state: restarted
      enabled: yes
      daemon_reload: yes
      name: monerod

  - name: Ensure the NetData Agent service is running
    service:
      name: netdata
      state: started
      enabled: yes

